### ISSUE TITLE
Failed first install plugin

### ISSUE THREAD

**Issue by reynave** [TheCocoaProject/cordova-plugin-nativestorage#135]
I cannot install through this plugin, I'm using 8.1.2 (cordova-lib@8.1.1), whats wrong ?

```
Installing "cordova-plugin-nativestorage" for android
ANDROID_HOME=C:\Users\kimihimi\AppData\Local\Android\android-sdk
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_191
Subproject Path: CordovaLib

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find manifest-merger.jar (com.android.tools.build:manifest-merger:26.0.0).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/build/manifest-merger/26.0.0/manifest-merger-26.0.0.jar
   > Could not find ddmlib.jar (com.android.tools.ddms:ddmlib:26.0.0).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/ddms/ddmlib/26.0.0/ddmlib-26.0.0.jar
   > Could not find dvlib.jar (com.android.tools:dvlib:26.0.0).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/dvlib/26.0.0/dvlib-26.0.0.jar
   > Could not find common.jar (com.android.tools:common:26.0.0).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/common/26.0.0/common-26.0.0.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
Failed to install 'cordova-plugin-nativestorage': Error: cmd: Command failed with exit code 1
    at ChildProcess.whenDone (C:\xampp\htdocs\nodejs\potobom\platforms\android\cordova\node_modules\cordova-common\src\superspawn.js:169:23)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
cmd: Command failed with exit code 1
```

**Comment by GillesC** [comment]
Could you consult issue #51 ?
