### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by appzer** [TheCocoaProject/cordova-plugin-nativestorage#51]
Hello,

i get the following error, when i install the plugin, what can i do?

```
AdminisorsiMac6:Pushsafer admin$ cordova plugin add cordova-plugin-nativestorage
Installing "cordova-plugin-nativestorage" for android
ANDROID_HOME=/Users/admin/Documents/adt-bundle/sdk
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home
Subproject Path: CordovaLib

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugApk'.
   > A problem occurred configuring project ':CordovaLib'.
      > Could not resolve all dependencies for configuration ':CordovaLib:class path'
         > Could not find com.android.tools.build:grade:2.2.2..
           Searched in the following locations:
               https://repo1.maven.org/maven2/com/android/tools/build/gradle/2.2.2/gradle-2.2.2.pom
               https://repo1.maven.org/maven2/com/android/tools/build/gradle/2.2.2/gradle-2.2.2.jar
           Required by:
               android:CordovaLib:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.333 secs
Failed to install 'cordova-plugin-nativestorage':Error: /Users/admin/Documents/Pushsafer/platforms/android/gradlew: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/admin/Documents/Pushsafer/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
Error: /Users/admin/Documents/Pushsafer/platforms/android/gradlew: Command failed with exit code 1
AdminisorsiMac6:Pushsafer admin$
```

Kevin

**Comment by GillesC** [comment]
Hello

It seems to be an issue with the Android SDK and not the plugin. See [this issue](https://github.com/phonegap/phonegap-plugin-push/issues/141) for more information on your error.

**Comment by appzer** [comment]
Hello,

i added the plugin manually, now it works

Kevin
